// Action Types for Application List.
export const GET_APP_LIST_REQUEST = 'GET_APP_LIST_REQUEST';
export const GET_APP_LIST_SUCCESS = 'GET_APP_LIST_SUCCESS';
export const GET_APP_LIST_FAILURE = 'GET_APP_LIST_FAILURE';
// Action List for Weather API.
export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_FAILURE = 'GET_WEATHER_FAILURE';
// Action List for Location details by serial number.
export const GET_LOCATION_BY_SERIAL_REQUEST = 'GET_LOCATION_BY_SERIAL_REQUEST';
export const GET_LOCATION_BY_SERIAL_SUCCESS = 'GET_LOCATION_BY_SERIAL_SUCCESS';
export const GET_LOCATION_BY_SERIAL_FAILURE = 'GET_LOCATION_BY_SERIAL_FAILURE';
// Action List for Image List.
export const GET_IMG_LIST_REQUEST = 'GET_IMG_LIST_REQUEST';
export const GET_IMG_LIST_SUCCESS = 'GET_IMG_LIST_SUCCESS';
export const GET_IMG_LIST_FAILURE = 'GET_IMG_LIST_FAILURE';
// Action Types for Profile data.
export const GET_PROFILE_DATA_REQUEST = 'GET_PROFILE_DATA_REQUEST';
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS';
export const GET_PROFILE_DATA_FAILURE = 'GET_PROFILE_DATA_FAILURE';
// Action Types for External Application List.
export const GET_EXT_APP_LIST_REQUEST = 'GET_EXT_APP_LIST_REQUEST';
export const GET_EXT_APP_LIST_SUCCESS = 'GET_EXT_APP_LIST_SUCCESS';
export const GET_EXT_APP_LIST_FAILURE = 'GET_EXT_APP_LIST_FAILURE';
// Action Types for Tenant specific custimization.
export const GET_TENANT_PROPS_REQUEST = 'GET_TENANT_PROPS_REQUEST';
export const GET_TENANT_PROPS_SUCCESS = 'GET_TENANT_PROPS_SUCCESS';
export const GET_TENANT_PROPS_FAILURE = 'GET_TENANT_PROPS_FAILURE';
// Action Types Admin specific props.
export const GET_ADMIN_PROPS_REQUEST = 'GET_ADMIN_PROPS_REQUEST';
export const GET_ADMIN_PROPS_SUCCESS = 'GET_ADMIN_PROPS_SUCCESS';
export const GET_ADMIN_PROPS_FAILURE = 'GET_ADMIN_PROPS_FAILURE';
// Action Types Theme configuration.
export const GET_THEME_PROPERTIES_REQUEST = 'GET_THEME_PROPERTIES_REQUEST';
export const GET_THEME_PROPERTIES_SUCCESS = 'GET_THEME_PROPERTIES_SUCCESS';
export const GET_THEME_PROPERTIES_FAILURE = 'GET_THEME_PROPERTIES_FAILURE';
// Action to Change the 'font size' in the application preference.
export const SET_APPLICATION_FONT_SIZE_PREFERENCE = 'SET_APPLICATION_FONT_SIZE_PREFERENCE';
