const VIDEO_ASSET_LIST = [
    {
        staged: false,
        title: 'Anaphylaxis',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1033.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            "Anaphylaxis is a potentially life-threatening allergic reaction. Common causes of anaphylaxis are allergies to penicillin, bee stings, aspirin, eggs, peanuts, and nuts. In this video, you'll find out other possible causes, what preventive steps you can take to avoid anaphylaxis, and why emergency treatment is needed.",
        contentVideoPk: '54',
        videoId: 'krames__V1033',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1033.jpg',
        duration: '05:35',
        uniqueProviderId: 'V1033',
        defaultTitle: 'Anaphylaxis',
        language: 'English',
        commonKey: 'krames__Allergic Reaction: Anaphylaxis',
        topLevelCategory: 'EDUCATION',
        category: 'Allergy, Ears-Nose-Throat, Emergency Medicine, Primary Care, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 30,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 0,
        maxAge: 120,
        availableWithoutAuth: false,
        hideInGuestMode: false,
        overallRating: '5.00',
        ageCategory: 'PG-13',
    },
    {
        staged: false,
        title: 'Allergic Rhinitis',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1027.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'Allergic rhinitis is also known as "hay fever." The symptoms can be seasonal, especially in the spring and fall, or year round. In this video, you\'ll learn what happens when you have allergic rhinitis and what you can do to minimize symptoms.',
        contentVideoPk: '52',
        videoId: 'krames__V1027',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1027.jpg',
        duration: '04:46',
        uniqueProviderId: 'V1027',
        defaultTitle: 'Allergic Rhinitis',
        language: 'English',
        commonKey: 'krames__Allergic Rhinitis',
        topLevelCategory: 'EDUCATION',
        category: 'Allergy, Ears-Nose-Throat, Primary Care, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 80,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 18,
        maxAge: 65,
        availableWithoutAuth: false,
        hideInGuestMode: false,
        overallRating: '4.00',
        ageCategory: 'PG',
    },
    {
        staged: false,
        title: 'Angioedema',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1104.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'Angioedema is a skin condition very similar to hives. In hives, raised, red, itchy, irregular bumps appear on the skin; in angioedema, the same thing happens beneath the skin. Instead of being itchy, angioedema is tender or painful. This video offers additional details about this condition and how it develops.',
        contentVideoPk: '92',
        videoId: 'krames__V1104',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1104.jpg',
        duration: '04:46',
        uniqueProviderId: 'V1104',
        defaultTitle: 'Angioedema',
        language: 'English',
        commonKey: 'krames__Allergic Reaction: Angioedema',
        topLevelCategory: 'EDUCATION',
        category: 'Allergy, Dermatology, Emergency Medicine, Primary Care, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 10,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 18,
        maxAge: 65,
        availableWithoutAuth: false,
        hideInGuestMode: false,
        overallRating: '3.00',
        ageCategory: 'PG-13',
    },
    {
        staged: false,
        title: 'Atopic Dermatitis',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1109.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'Atopic dermatitis is a skin inflammation caused by sensitivity to something in the environment. It often runs in families and may occur along with hay fever, asthma, or nasal allergies. This video explores the possible triggers for the condition and who is at risk.',
        contentVideoPk: '95',
        videoId: 'krames__V1109',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1109.jpg',
        duration: '05:19',
        uniqueProviderId: 'V1109',
        defaultTitle: 'Atopic Dermatitis',
        language: 'English',
        commonKey: 'krames__Atopic Dermatitis',
        topLevelCategory: 'EDUCATION',
        category: 'Allergy, Dermatology, Pediatrics, Primary Care',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 0,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 0,
        maxAge: 120,
        availableWithoutAuth: false,
        hideInGuestMode: false,
        overallRating: '3.50',
        ageCategory: 'PG-17',
    },
    {
        staged: false,
        title: 'Metered-Dose Inhaler',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1172.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            "An MDI is the most commonly used inhaler in treating lung diseases such as asthma and COPD. Unfortunately, many people who need an inhaler do not use it correctly, so they don't receive the full benefit of the medication. Watch this video to learn the best way to use your inhaler.",
        contentVideoPk: '118',
        videoId: 'krames__W1172',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1172.jpg',
        duration: '06:13',
        uniqueProviderId: 'W1172',
        defaultTitle: 'Metered-Dose Inhaler',
        language: 'English',
        commonKey: 'krames__Metered-Dose Inhaler',
        topLevelCategory: 'EDUCATION',
        category: 'Primary Care, Allergy, Ears-Nose-Throat, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 100,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 1,
        maxAge: 120,
        availableWithoutAuth: false,
        hideInGuestMode: false,
        overallRating: '4.50',
        ageCategory: 'PG-17',
    },
    {
        staged: false,
        title: 'Peak Flow Meter',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1173.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'A peak flow meter for asthma is like a thermometer for a fever (it helps you monitor what\'s going on inside your lungs by measuring airflow out of the lungs. The meter can tell you if your airways are narrowing well before asthma symptoms begin. Learn how to use a peak flow meter, how to find your "personal best," and how to set your peak flow zones.)',
        contentVideoPk: '119',
        videoId: 'krames__W1173',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1173.jpg',
        duration: '06:12',
        uniqueProviderId: 'W1173',
        defaultTitle: 'Peak Flow Meter',
        language: 'English',
        commonKey: 'krames__Peak Flow Meter',
        topLevelCategory: 'EDUCATION',
        category: 'Primary Care, Allergy, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 30,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 1,
        maxAge: 120,
        availableWithoutAuth: false,
        hideInGuestMode: false,
        overallRating: '2.00',
        ageCategory: 'PG',
    },
    {
        staged: false,
        title: 'Asthma',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1503.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'Asthma is a chronic respiratory condition that causes inflammation of the airways. This inflammation, which can be triggered by a variety of substances, makes the airways much narrower and interferes with breathing. This video discusses who is at risk for this condition and how it can be managed.',
        contentVideoPk: '193',
        videoId: 'krames__W1503',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1503.jpg',
        duration: '04:14',
        uniqueProviderId: 'W1503',
        defaultTitle: 'Asthma',
        language: 'English',
        commonKey: 'krames__Asthma',
        topLevelCategory: 'EDUCATION',
        category: 'Primary Care, Allergy, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 0,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 1,
        maxAge: 120,
        availableWithoutAuth: false,
        hideInGuestMode: false,
        overallRating: '4.00',
        ageCategory: 'PG-17',
    },
    {
        staged: false,
        title: 'Allergic Rhinitis',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1027.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'Allergic rhinitis is also known as "hay fever." The symptoms can be seasonal, especially in the spring and fall, or year round. In this video, you\'ll learn what happens when you have allergic rhinitis and what you can do to minimize symptoms.',
        contentVideoPk: '52',
        videoId: 'krames__V1027',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1027.jpg',
        duration: '04:46',
        uniqueProviderId: 'V1027',
        defaultTitle: 'Allergic Rhinitis',
        language: 'English',
        commonKey: 'krames__Allergic Rhinitis',
        topLevelCategory: 'EDUCATION',
        category: 'Allergy, Ears-Nose-Throat, Primary Care, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 80,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 18,
        maxAge: 65,
        availableWithoutAuth: false,
        hideInGuestMode: false,
        overallRating: '4.00',
        ageCategory: 'PG',
    },
    {
        staged: false,
        title: 'Allergic Rhinitis',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1027.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'Allergic rhinitis is also known as "hay fever." The symptoms can be seasonal, especially in the spring and fall, or year round. In this video, you\'ll learn what happens when you have allergic rhinitis and what you can do to minimize symptoms.',
        contentVideoPk: '52',
        videoId: 'krames__V1027',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1027.jpg',
        duration: '04:46',
        uniqueProviderId: 'V1027',
        defaultTitle: 'Allergic Rhinitis',
        language: 'English',
        commonKey: 'krames__Allergic Rhinitis',
        topLevelCategory: 'EDUCATION',
        category: 'Allergy, Ears-Nose-Throat, Primary Care, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 80,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 18,
        maxAge: 65,
        availableWithoutAuth: false,
        hideInGuestMode: false,
        overallRating: '4.00',
        ageCategory: 'PG',
    },
    {
        staged: false,
        title: 'Allergic Rhinitis',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1027.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'Allergic rhinitis is also known as "hay fever." The symptoms can be seasonal, especially in the spring and fall, or year round. In this video, you\'ll learn what happens when you have allergic rhinitis and what you can do to minimize symptoms.',
        contentVideoPk: '52',
        videoId: 'krames__V1027',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1027.jpg',
        duration: '04:46',
        uniqueProviderId: 'V1027',
        defaultTitle: 'Allergic Rhinitis',
        language: 'English',
        commonKey: 'krames__Allergic Rhinitis',
        topLevelCategory: 'EDUCATION',
        category: 'Allergy, Ears-Nose-Throat, Primary Care, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 80,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 18,
        maxAge: 65,
        availableWithoutAuth: false,
        hideInGuestMode: false,
        overallRating: '4.00',
        ageCategory: 'PG',
    },
];

// TODO: This is dummy data added for demo purpose.
const VIDEO_BREADCRUMB_DATA = [
    {
        breadcrumbLabel: 'Education',
        isUnderlineRequired: true,
        breadcrumbLink: '',
        stylingClasses: '',
    },
    {
        breadcrumbLabel: 'Allergy',
        isUnderlineRequired: false,
        breadcrumbLink: '',
        stylingClasses: '',
    },
];

/**
 * This is the function used to update the breadcrumb value.
 * @param labelValue {string}
 */
function setBreadcrumbElementLabel(labelValue: string) {
    console.log('setBreadcrumbElementLabel labelValue=', labelValue);
    VIDEO_BREADCRUMB_DATA.map((breadCrumbElement) => {
        if (!breadCrumbElement.isUnderlineRequired) {
            // VIDEO_BREADCRUMB_DATA[index].categoryLabel = labelValue;
        }
    });
    return VIDEO_BREADCRUMB_DATA;
}
const VERTICAL_MENU_FOCUS_KEY = 'MENU';

export { VIDEO_ASSET_LIST, VERTICAL_MENU_FOCUS_KEY, VIDEO_BREADCRUMB_DATA, setBreadcrumbElementLabel };
