const CATEGORIES = [
    {
        categoryName: 'Allergy',
        id: 'Allergy',
    },
    {
        categoryName: 'Pediatrics',
        id: 'Pediatrics',
    },
    {
        categoryName: 'Nephrology',
        id: 'Nephrology',
    },
    {
        categoryName: "Women's Health",
        id: "Women's Health",
    },
    {
        categoryName: 'Senior Health',
        id: 'Senior Health',
    },
    {
        categoryName: 'Wellness',
        id: 'Wellness',
    },
    {
        categoryName: 'Oncology',
        id: 'Oncology',
    },
    {
        categoryName: 'Mental Health',
        id: 'Mental Health',
    },
    {
        categoryName: 'Health & Wellness',
        id: 'Health & Wellness',
    },
    {
        categoryName: 'General Surgery',
        id: 'General Surgery',
    },
    {
        categoryName: 'Urology',
        id: 'Urology',
    },
    {
        categoryName: 'Imaging',
        id: 'Imaging',
    },
    {
        categoryName: 'Gastroenterology',
        id: 'Gastroenterology',
    },
    {
        categoryName: 'Ophthalmology',
        id: 'Ophthalmology',
    },
    {
        categoryName: 'Cardiology',
        id: 'Cardiology',
    },
    {
        categoryName: 'Emergency Medicine',
        id: 'Emergency Medicine',
    },
    {
        categoryName: 'Nutrition',
        id: 'Nutrition',
    },
    {
        categoryName: 'Dermatology',
        id: 'Dermatology',
    },
    {
        categoryName: 'OB/GYN',
        id: 'OB/GYN',
    },
    {
        categoryName: 'Rheumatology',
        id: 'Rheumatology',
    },
    {
        categoryName: 'Ears-Nose-Throat',
        id: 'Ears-Nose-Throat',
    },
    {
        categoryName: 'Respiratory',
        id: 'Respiratory',
    },
    {
        categoryName: 'Vascular',
        id: 'Vascular',
    },
    {
        categoryName: 'Neurology',
        id: 'Neurology',
    },
    {
        categoryName: 'Orthopedics',
        id: 'Orthopedics',
    },
    {
        categoryName: 'Radiology',
        id: 'Radiology',
    },
    {
        categoryName: 'Primary Care',
        id: 'Primary Care',
    },
    {
        categoryName: 'Pulmonary',
        id: 'Pulmonary',
    },
    {
        categoryName: 'Endocrinology',
        id: 'Endocrinology',
    },
];

const CONTENT_VIDEO_LIST = [
    {
        availableInLanguages: [
            {
                staged: false,
                title: 'Allergic Reaction: Anaphylaxis',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1033.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    "Anaphylaxis is a potentially life-threatening allergic reaction. Common causes of anaphylaxis are allergies to penicillin, bee stings, aspirin, eggs, peanuts, and nuts. In this video, you'll find out other possible causes, what preventive steps you can take to avoid anaphylaxis, and why emergency treatment is needed.",
                contentVideoPk: '54',
                videoId: 'krames__V1033',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1033.jpg',
                duration: '05:35',
                uniqueProviderId: 'V1033',
                defaultTitle: 'Allergic Reaction: Anaphylaxis',
                language: 'English',
                commonKey: 'krames__Allergic Reaction: Anaphylaxis',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    dateCreated: 1634821036219,
                    userId: 'phil',
                    contentVideoPk: '54',
                    videoId: 'krames__V1033',
                    viewedPercentage: 0,
                    position: '00:00:00',
                    viewCount: 0,
                    isMandatory: false,
                    assignedBy: 'VOLUNTARY',
                    commonKey: 'krames__Allergic Reaction: Anaphylaxis',
                    language: 'English',
                    topLevelCategory: 'EDUCATION',
                    dateUpdated: 1649243867295,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
            {
                staged: false,
                title: 'Allergic Reaction: Anaphylaxis',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1827.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    "Anaphylaxis is a potentially life-threatening allergic reaction. Common causes of anaphylaxis are allergies to penicillin, bee stings, aspirin, eggs, peanuts, and nuts. In this video, you'll find out other possible causes, what preventive steps you can take to avoid anaphylaxis, and why emergency treatment is needed.",
                contentVideoPk: '289',
                videoId: 'krames__W1827',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1827.jpg',
                duration: '06:51',
                uniqueProviderId: 'W1827',
                defaultTitle: 'Allergic Reaction: Anaphylaxis',
                language: 'Spanish',
                commonKey: 'krames__Allergic Reaction: Anaphylaxis',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
        ],
        staged: false,
        title: 'Allergic Reaction: Anaphylaxis',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1033.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            "Anaphylaxis is a potentially life-threatening allergic reaction. Common causes of anaphylaxis are allergies to penicillin, bee stings, aspirin, eggs, peanuts, and nuts. In this video, you'll find out other possible causes, what preventive steps you can take to avoid anaphylaxis, and why emergency treatment is needed.",
        contentVideoPk: '54',
        videoId: 'krames__V1033',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1033.jpg',
        duration: '05:35',
        uniqueProviderId: 'V1033',
        defaultTitle: 'Allergic Reaction: Anaphylaxis',
        language: 'English',
        commonKey: 'krames__Allergic Reaction: Anaphylaxis',
        topLevelCategory: 'EDUCATION',
        category: 'Allergy, Ears-Nose-Throat, Emergency Medicine, Primary Care, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 0,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 0,
        maxAge: 120,
        availableWithoutAuth: false,
        hideInGuestMode: false,
    },
    {
        availableInLanguages: [
            {
                staged: false,
                title: 'Allergic Rhinitis',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1027.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    'Allergic rhinitis is also known as "hay fever." The symptoms can be seasonal, especially in the spring and fall, or year round. In this video, you\'ll learn what happens when you have allergic rhinitis and what you can do to minimize symptoms.',
                contentVideoPk: '52',
                videoId: 'krames__V1027',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1027.jpg',
                duration: '04:46',
                uniqueProviderId: 'V1027',
                defaultTitle: 'Allergic Rhinitis',
                language: 'English',
                commonKey: 'krames__Allergic Rhinitis',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
            {
                staged: false,
                title: 'RINITIS ALÉRGICA',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1829.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    'Allergic rhinitis is also known as "hay fever." The symptoms can be seasonal, especially in the spring and fall, or year round. In this video, you\'ll learn what happens when you have allergic rhinitis and what you can do to minimize symptoms.',
                contentVideoPk: '291',
                videoId: 'krames__W1829',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1829.jpg',
                duration: '05:42',
                uniqueProviderId: 'W1829',
                defaultTitle: 'Allergic Rhinitis',
                language: 'Spanish',
                commonKey: 'krames__Allergic Rhinitis',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
        ],
        staged: false,
        title: 'Allergic Rhinitis',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1027.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'Allergic rhinitis is also known as "hay fever." The symptoms can be seasonal, especially in the spring and fall, or year round. In this video, you\'ll learn what happens when you have allergic rhinitis and what you can do to minimize symptoms.',
        contentVideoPk: '52',
        videoId: 'krames__V1027',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1027.jpg',
        duration: '04:46',
        uniqueProviderId: 'V1027',
        defaultTitle: 'Allergic Rhinitis',
        language: 'English',
        commonKey: 'krames__Allergic Rhinitis',
        topLevelCategory: 'EDUCATION',
        category: 'Allergy, Ears-Nose-Throat, Primary Care, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 0,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 18,
        maxAge: 65,
        availableWithoutAuth: false,
        hideInGuestMode: false,
    },
    {
        availableInLanguages: [
            {
                staged: false,
                title: 'Allergic Reaction: Angioedema',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1104.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    'Angioedema is a skin condition very similar to hives. In hives, raised, red, itchy, irregular bumps appear on the skin; in angioedema, the same thing happens beneath the skin. Instead of being itchy, angioedema is tender or painful. This video offers additional details about this condition and how it develops.',
                contentVideoPk: '92',
                videoId: 'krames__V1104',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1104.jpg',
                duration: '04:46',
                uniqueProviderId: 'V1104',
                defaultTitle: 'Allergic Reaction: Angioedema',
                language: 'English',
                commonKey: 'krames__Allergic Reaction: Angioedema',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
            {
                staged: false,
                title: 'Allergic Reaction: Angioedema',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1828.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    'Angioedema is a skin condition very similar to hives. In hives, raised, red, itchy, irregular bumps appear on the skin; in angioedema, the same thing happens beneath the skin. Instead of being itchy, angioedema is tender or painful. This video offers additional details about this condition and how it develops.',
                contentVideoPk: '290',
                videoId: 'krames__W1828',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1828.jpg',
                duration: '05:06',
                uniqueProviderId: 'W1828',
                defaultTitle: 'Allergic Reaction: Angioedema',
                language: 'Spanish',
                commonKey: 'krames__Allergic Reaction: Angioedema',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
        ],
        staged: false,
        title: 'Allergic Reaction: Angioedema',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1104.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'Angioedema is a skin condition very similar to hives. In hives, raised, red, itchy, irregular bumps appear on the skin; in angioedema, the same thing happens beneath the skin. Instead of being itchy, angioedema is tender or painful. This video offers additional details about this condition and how it develops.',
        contentVideoPk: '92',
        videoId: 'krames__V1104',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1104.jpg',
        duration: '04:46',
        uniqueProviderId: 'V1104',
        defaultTitle: 'Allergic Reaction: Angioedema',
        language: 'English',
        commonKey: 'krames__Allergic Reaction: Angioedema',
        topLevelCategory: 'EDUCATION',
        category: 'Allergy, Dermatology, Emergency Medicine, Primary Care, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 0,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 18,
        maxAge: 65,
        availableWithoutAuth: false,
        hideInGuestMode: false,
    },
    {
        availableInLanguages: [
            {
                staged: false,
                title: 'Atopic Dermatitis',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1109.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    'Atopic dermatitis is a skin inflammation caused by sensitivity to something in the environment. It often runs in families and may occur along with hay fever, asthma, or nasal allergies. This video explores the possible triggers for the condition and who is at risk.',
                contentVideoPk: '95',
                videoId: 'krames__V1109',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1109.jpg',
                duration: '05:19',
                uniqueProviderId: 'V1109',
                defaultTitle: 'Atopic Dermatitis',
                language: 'English',
                commonKey: 'krames__Atopic Dermatitis',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    dateCreated: 1649238987938,
                    userId: 'phil',
                    contentVideoPk: '95',
                    videoId: 'krames__V1109',
                    viewedPercentage: 0,
                    position: '00:00:00',
                    viewCount: 0,
                    isMandatory: false,
                    assignedBy: 'VOLUNTARY',
                    commonKey: 'krames__Atopic Dermatitis',
                    language: 'English',
                    topLevelCategory: 'EDUCATION',
                    dateUpdated: 1649239006839,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
            {
                staged: false,
                title: 'DERMATITIS ATÓPICA',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1869.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    'Atopic dermatitis is a skin inflammation caused by sensitivity to something in the environment. It often runs in families and may occur along with hay fever, asthma, or nasal allergies. This video explores the possible triggers for the condition and who is at risk.',
                contentVideoPk: '331',
                videoId: 'krames__W1869',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1869.jpg',
                duration: '05:19',
                uniqueProviderId: 'W1869',
                defaultTitle: 'Atopic Dermatitis',
                language: 'Spanish',
                commonKey: 'krames__Atopic Dermatitis',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
        ],
        staged: false,
        title: 'Atopic Dermatitis',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/V1109.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'Atopic dermatitis is a skin inflammation caused by sensitivity to something in the environment. It often runs in families and may occur along with hay fever, asthma, or nasal allergies. This video explores the possible triggers for the condition and who is at risk.',
        contentVideoPk: '95',
        videoId: 'krames__V1109',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/V1109.jpg',
        duration: '05:19',
        uniqueProviderId: 'V1109',
        defaultTitle: 'Atopic Dermatitis',
        language: 'English',
        commonKey: 'krames__Atopic Dermatitis',
        topLevelCategory: 'EDUCATION',
        category: 'Allergy, Dermatology, Pediatrics, Primary Care',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 0,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 0,
        maxAge: 120,
        availableWithoutAuth: false,
        hideInGuestMode: false,
    },
    {
        availableInLanguages: [
            {
                staged: false,
                title: 'Metered-Dose Inhaler',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1172.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    "An MDI is the most commonly used inhaler in treating lung diseases such as asthma and COPD. Unfortunately, many people who need an inhaler do not use it correctly, so they don't receive the full benefit of the medication. Watch this video to learn the best way to use your inhaler.",
                contentVideoPk: '118',
                videoId: 'krames__W1172',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1172.jpg',
                duration: '06:13',
                uniqueProviderId: 'W1172',
                defaultTitle: 'Metered-Dose Inhaler',
                language: 'English',
                commonKey: 'krames__Metered-Dose Inhaler',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
            {
                staged: false,
                title: 'INHALADOR DE DOSIS FIJA',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1223.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    "An MDI is the most commonly used inhaler in treating lung diseases such as asthma and COPD. Unfortunately, many people who need an inhaler do not use it correctly, so they don't receive the full benefit of the medication. Watch this video to learn the best way to use your inhaler.",
                contentVideoPk: '128',
                videoId: 'krames__W1223',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1223.jpg',
                duration: '06:15',
                uniqueProviderId: 'W1223',
                defaultTitle: 'Metered-Dose Inhaler',
                language: 'Spanish',
                commonKey: 'krames__Metered-Dose Inhaler',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
            {
                staged: false,
                title: 'INHALATOR CISNIENIOWY Z DOZOWNIKIEM',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1383.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    'Overview of the device as treatment for asthma and chronic obstructive pulmonary disease. Presents clear information on components, use and care. -3 common methods for use -Properly caring for your inhaler -Encourages users to learn the best method and to practice',
                contentVideoPk: '171',
                videoId: 'krames__W1383',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1383.jpg',
                duration: '07:32',
                uniqueProviderId: 'W1383',
                defaultTitle: 'Metered-Dose Inhaler',
                language: 'Polish',
                commonKey: 'krames__Metered-Dose Inhaler',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
        ],
        staged: false,
        title: 'Metered-Dose Inhaler',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1172.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            "An MDI is the most commonly used inhaler in treating lung diseases such as asthma and COPD. Unfortunately, many people who need an inhaler do not use it correctly, so they don't receive the full benefit of the medication. Watch this video to learn the best way to use your inhaler.",
        contentVideoPk: '118',
        videoId: 'krames__W1172',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1172.jpg',
        duration: '06:13',
        uniqueProviderId: 'W1172',
        defaultTitle: 'Metered-Dose Inhaler',
        language: 'English',
        commonKey: 'krames__Metered-Dose Inhaler',
        topLevelCategory: 'EDUCATION',
        category: 'Primary Care, Allergy, Ears-Nose-Throat, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 0,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 1,
        maxAge: 120,
        availableWithoutAuth: false,
        hideInGuestMode: false,
    },
    {
        availableInLanguages: [
            {
                staged: false,
                title: 'Peak Flow Meter',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1173.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    'A peak flow meter for asthma is like a thermometer for a fever (it helps you monitor what\'s going on inside your lungs by measuring airflow out of the lungs. The meter can tell you if your airways are narrowing well before asthma symptoms begin. Learn how to use a peak flow meter, how to find your "personal best," and how to set your peak flow zones.)',
                contentVideoPk: '119',
                videoId: 'krames__W1173',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1173.jpg',
                duration: '06:12',
                uniqueProviderId: 'W1173',
                defaultTitle: 'Peak Flow Meter',
                language: 'English',
                commonKey: 'krames__Peak Flow Meter',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
            {
                staged: false,
                title: 'MEDIDOR DE FLUJO DE AIRE MÁXIMO',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1224.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    'A peak flow meter for asthma is like a thermometer for a fever (it helps you monitor what\'s going on inside your lungs by measuring airflow out of the lungs. The meter can tell you if your airways are narrowing well before asthma symptoms begin. Learn how to use a peak flow meter, how to find your "personal best," and how to set your peak flow zones.)',
                contentVideoPk: '129',
                videoId: 'krames__W1224',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1224.jpg',
                duration: '06:22',
                uniqueProviderId: 'W1224',
                defaultTitle: 'Peak Flow Meter',
                language: 'Spanish',
                commonKey: 'krames__Peak Flow Meter',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
        ],
        staged: false,
        title: 'Peak Flow Meter',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1173.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'A peak flow meter for asthma is like a thermometer for a fever (it helps you monitor what\'s going on inside your lungs by measuring airflow out of the lungs. The meter can tell you if your airways are narrowing well before asthma symptoms begin. Learn how to use a peak flow meter, how to find your "personal best," and how to set your peak flow zones.)',
        contentVideoPk: '119',
        videoId: 'krames__W1173',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1173.jpg',
        duration: '06:12',
        uniqueProviderId: 'W1173',
        defaultTitle: 'Peak Flow Meter',
        language: 'English',
        commonKey: 'krames__Peak Flow Meter',
        topLevelCategory: 'EDUCATION',
        category: 'Primary Care, Allergy, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 0,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 1,
        maxAge: 120,
        availableWithoutAuth: false,
        hideInGuestMode: false,
    },
    {
        availableInLanguages: [
            {
                staged: false,
                title: 'Asthma',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1503.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    'Asthma is a chronic respiratory condition that causes inflammation of the airways. This inflammation, which can be triggered by a variety of substances, makes the airways much narrower and interferes with breathing. This video discusses who is at risk for this condition and how it can be managed.',
                contentVideoPk: '193',
                videoId: 'krames__W1503',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1503.jpg',
                duration: '04:14',
                uniqueProviderId: 'W1503',
                defaultTitle: 'Asthma',
                language: 'English',
                commonKey: 'krames__Asthma',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
            {
                staged: false,
                title: 'ASMA',
                httpUri:
                    'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1504.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
                description:
                    'Asthma is a chronic respiratory condition that causes inflammation of the airways. This inflammation, which can be triggered by a variety of substances, makes the airways much narrower and interferes with breathing. This video discusses who is at risk for this condition and how it can be managed.',
                contentVideoPk: '194',
                videoId: 'krames__W1504',
                thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1504.jpg',
                duration: '04:33',
                uniqueProviderId: 'W1504',
                defaultTitle: 'Asthma',
                language: 'Spanish',
                commonKey: 'krames__Asthma',
                topLevelCategory: 'EDUCATION',
                external: false,
                providerId: 'krames',
                contentVideoProgressVO: {
                    viewedPercentage: 0,
                    viewCount: 0,
                },
                minAge: 0,
                maxAge: 0,
                availableWithoutAuth: false,
                hideInGuestMode: false,
            },
        ],
        staged: false,
        title: 'Asthma',
        httpUri:
            'https://pxstorageaccount.blob.core.windows.net/videos/vd2/site/krames/W1503.mp4?sp=r&st=2022-02-11T07:53:49Z&se=2022-02-13T15:53:49Z&spr=https&sv=2020-08-04&sr=c&sig=1KqjEuGyVc52JnBudswLNANwWDbkUQUIAMCCggo99mc%3D',
        description:
            'Asthma is a chronic respiratory condition that causes inflammation of the airways. This inflammation, which can be triggered by a variety of substances, makes the airways much narrower and interferes with breathing. This video discusses who is at risk for this condition and how it can be managed.',
        contentVideoPk: '193',
        videoId: 'krames__W1503',
        thumbnailUri: 'https://pxstorageaccount.blob.core.windows.net/videos/tn2/site/krames/W1503.jpg',
        duration: '04:14',
        uniqueProviderId: 'W1503',
        defaultTitle: 'Asthma',
        language: 'English',
        commonKey: 'krames__Asthma',
        topLevelCategory: 'EDUCATION',
        category: 'Primary Care, Allergy, Pulmonary, Respiratory',
        external: false,
        providerId: 'krames',
        contentVideoProgressVO: {
            viewedPercentage: 0,
            viewCount: 0,
        },
        libraries: ['EDUCATION'],
        type: 'video',
        minAge: 1,
        maxAge: 120,
        availableWithoutAuth: false,
        hideInGuestMode: false,
    },
];

export { CATEGORIES, CONTENT_VIDEO_LIST };
