export const appConfigTV: any = {
    externalappsBaseKey: 'patientapp.extapp.',
    OAuth: {
        enableOAuth: false,
        OAuthAPI: '/iep/token/generate',
        RevokeTokenAPI: '/iep/token/revoke',
        OAuthTokenExpiryTime: 3600,
        TimeBeforeExpiryForTokenRefresh: 300,
        OAuthTokenType: 'Bearer',
        OAuthBaseVersion: '/v2',
        OAuthTokenGenerationCredentials: {
            guestApp: {
                consumerKey: 'guestApp',
                consumerSecret: 'extPC3@sta',
                siteUserName: 'site_guest@px.com',
                tenantUserName: 'guest@tenantId.com',
                userName: 'guest',
                basicAuth: 'Basic SlI5d0RHaGxzVEN1X2pDREJuRkxpaVNwUVg0YTpiUzMyUjV6RVcxZmY2NzJfazVaWkFnSGYzcllh',
                scope: 'content_read config_read location_read locationpref_write tvguide_read speeddial_read operator_read collaboration_read collaboration_write',
            },
            patientApp: {
                consumer_key: 'patientApp',
                consumer_secret: 'extPC3@sta',
                scope: 'patient_read patient_write config_read location_read locationpref_write tvguide_read speeddial_read speeddial_write collaboration_read collaboration_write workflow_read workflow_write operator_read survey_read request_read question_read faqs_read foodmenu_read foodmenu_write content_read',
            },
        },
    },
    patientProfile: {
        messageSequence: 0,
        endpoint: '',
        primaryDoctorFirstName: '',
        primaryDoctorLastName: '',
        primaryDoctorDisplayName: '',
        primaryNurseFirstname: '',
        primaryNurseLastname: '',
        primaryNurseDisplayName: '',
        emrRefId: '',
        patientId: '',
        patientType: 'NOT_SPECIFIED',
        patientHasPreferences: {
            language: 'en_US',
            showNotifications: true,
            showFooter: true,
            fontSize: 'medium',
            phoneRinger: true,
            videoCall: true,
            presenceDoNotDisturb: false,
            nameDisplayFormat: 'FIRST_NAME_ONLY',
            privacyDataUnLockDuration: '60',
            privacyDataLock: false,
            showClosedCaption: null,
            closedCaption: null,
        },
        phonePreferences: {
            autoAnswerAsAudio: false,
            autoAnswerAsVideo: false,
            videoCallAutoAnswerExpiryTime: 10,
            lastUpdatedTime: 0,
        },
        patientName: {
            firstName: '',
            lastName: '',
        },
        userByUser: {
            firstName: '',
            lastName: '',
        },
        preferredAlias: {
            nameType: '',
            lastName: '',
            firstName: '',
            displayName: '',
            aliasId: 0,
        },
        diagnosisList: [
            {
                code: '',
                name: '',
                method: '',
            },
        ],
        patientLocation: {
            patientLocationPk: 0,
            room: '',
            bed: '',
            facility: '',
            floor: '',
            building: '',
            department: {
                departmentName: '',
                departmentId: '0',
            },
        },
        admittedTime: null,
        nurseId: '',
        doctorId: '',
        emrDoctorId: '',
        primaryDoctorImageUrl: ':defaultImagePath:common/staff.png',
        primaryNurseImageUrl: ':defaultImagePath:common/staff.png',
        estimatedDischargeTime: null,
        age: '14',
        gender: '',
        ageCategory: 'G',
    },
    locationDetailsPayload: {
        department: {
            departmentName: '',
            departmentId: '0',
        },
        facility: '',
        building: '',
        floor: '',
        room: '',
        bed: '',
        facilityDescription: '',
        buildingDescription: '',
        floorDescription: '',
        roomDescription: '',
        bedDescription: '',
        rbLocation: '',
        rtlsLocation: '',
        device: {
            serialNumber: '',
        },
        policy: {
            sipPhoneNumber: '',
            sipUser: '',
            sipPassword: '',
            callMgrHost: '',
        },
        locationType: 'WAITING_ROOM',
        locationId: '',
        outboundQueues: [],
        preferences: {
            language: 'en_US',
            fontSize: 'medium',
            createdDate: 0,
            updatedDate: 0,
            showClosedCaption: null,
            closedCaption: null,
            liveTvProtocolsMediaPlayer: 'UDP',
            liveTvProtocolsMobile: 'HLS',
            liveTvProtocolsMobileIOS: 'HLS',
            liveTvProtocolsMobileAndroid: 'HLS',
        },
    },
    nuxeoImageTags: {
        home: 'tvapp.app.home',
        back: 'tvapp.app.back',
        headerLogo: 'tvapp.header.customer.logo',
        footerLogo: 'tvapp.footer.supplier.logo',
        defaultStaffImage: 'tvapp.app.defaultstaff',
        patientAppWallpaper: 'patientapp.wallpaper',
        headerIcons: {
            PHONERINGER_ENABLED: 'tvapp.app.phoneringer.enabled',
            PHONERINGER_DISABLED: 'tvapp.app.phoneringer.disabled',
            PHONECAMERA_ENABLED: 'tvapp.app.camera.enabled',
            PHONECAMERA_DISABLED: 'tvapp.app.camera.disabled',
            PRIVACY_LOCK: 'tvapp.app.privacy.lock',
            PRIVACY_UNLOCK: 'tvapp.app.privacy.unlock',
            APPS_PRIVACY_LOCK: 'tvapp.app.lockindicator',
            PHONE_AUTO_ANSWER_ACTIVATED: 'tvapp.app.phone.preference.autoanswer.activated',
        },
        operatorMessageIndicators: {
            emergency: 'tvapp.operatormessage.emergency',
            warning: 'tvapp.operatormessage.warning',
            information: 'tvapp.operatormessage.information',
        },
        appImages: {
            screenSharing: 'tvapp.app.screenshare',
            myVisit: 'tvapp.app.myvisit',
            TVGuide: 'tvapp.app.tvguide',
            phone: 'tvapp.app.phone',
            dialPad: 'tvapp.app.phone.dialpad',
            callHistory: 'tvapp.app.phone.callhistory',
            myvideos: 'tvapp.app.myvideos',
            education: 'tvapp.app.videolibrary',
            relaxation: 'tvapp.app.relaxation',
            moviesOnDemand: 'tvapp.app.moviesondemand',
            settings: 'tvapp.app.settings',
            howTouseVideo: 'tvapp.app.howtousevideo',
            goal: 'tvapp.app.goal',
            painScore: 'tvapp.app.painscore',
            schedule: 'tvapp.app.schedule',
            foodMenu: 'tvapp.app.foodmenu',
            faq: 'tvapp.app.faq',
            progress: 'tvapp.app.progress',
            careTeamVisits: 'tvapp.app.careteamvisits',
            messages: 'tvapp.app.messages',
            questions: 'tvapp.app.messages.questions',
            inbox: 'tvapp.app.messages.inbox',
            requests: 'tvapp.app.requests',
            feedback: 'tvapp.app.feedback',
            medications: 'tvapp.app.medications',
            careTeam: 'tvapp.app.mycareteam',
            notifications: 'tvapp.app.notifications',
            profile: 'tvapp.app.patientprofile',
            friendsnfamily: 'tvapp.app.friendsnfamily',
            entertainment: 'tvapp.app.entertainment',
            games: 'tvapp.app.games',
        },
        appImagesSelected: {
            myVisit: 'tvapp.app.myvisit.selected',
            TVGuide: 'tvapp.app.tvguide.selected',
            phone: 'tvapp.app.phone.selected',
            myvideos: 'tvapp.app.myvideos.selected',
            education: 'tvapp.app.videolibrary.selected',
            relaxation: 'tvapp.app.relaxation.selected',
            moviesOnDemand: 'tvapp.app.moviesondemand.selected',
            settings: 'tvapp.app.settings.selected',
            howTouseVideo: 'tvapp.app.howtousevideo.selected',
            goal: 'tvapp.app.goal.selected',
            painScore: 'tvapp.app.painscore.selected',
            schedule: 'tvapp.app.schedule.selected',
            foodMenu: 'tvapp.app.foodmenu.selected',
            faq: 'tvapp.app.faq.selected',
            progress: 'tvapp.app.progress.selected',
            careTeamVisits: 'tvapp.app.careteamvisits.selected',
            messages: 'tvapp.app.messages.selected',
            requests: 'tvapp.app.requests.selected',
            feedback: 'tvapp.app.feedback.selected',
            medications: 'tvapp.app.medications.selected',
            careTeam: 'tvapp.app.mycareteam.selected',
            notifications: 'tvapp.app.notifications.selected',
            profile: 'tvapp.app.patientprofile.selected',
            friendsnfamily: 'tvapp.app.friendsnfamily.selected',
            entertainment: 'tvapp.app.entertainment.selected',
            games: 'tvapp.app.games.selected',
        },
        presenceStatusIndicators: {
            AVAILABLE: 'tvapp.app.presence.available',
            WATCHING_TV: 'tvapp.app.presence.watchingtv',
            ON_CALL: 'tvapp.app.presence.onacall',
            STAFF_IN_ROOM: 'tvapp.app.presence.staffinroom',
            DND: 'tvapp.app.presence.donotdisturb',
            SCREEN_SHARING: 'tvapp.app.presence.screenshare',
            OUT_OF_ROOM: 'tvapp.app.presence.outofroom',
        },
        settingsIcons: {
            presenceStatus: 'tvapp.preferences.available',
            notifications: 'tvapp.preferences.notifications',
            phoneRinger: 'tvapp.preferences.phoneringer',
            videoCamera: 'tvapp.preferences.videocamera',
            showFooter: 'tvapp.preferences.showfooter',
            closedCaptioning: 'tvapp.preferences.cc',
            privacyLock: 'tvapp.preferences.privacystatus',
            fontSize: 'tvapp.preferences.fontsize',
            language: 'tvapp.preferences.language',
        },
        goalDetails: 'tvapp.app.goal.details',
        messageDetails: 'tvapp.app.messages.details',
        requestDetails: 'tvapp.app.requests.details',
    },
    HomePageApps: [
        {
            id: 'MY_VISIT',
            order: 1,
            resourceId: 'common_apps_myvisit_label',
            state: 'INDEX_MY_VISIT',
            imageTag: 'myVisit',
            show: true,
        },
        {
            id: 'LIVE_TV',
            order: 2,
            resourceId: 'common_apps_live_tv_label',
            state: 'INDEX_TV_GUIDE',
            imageTag: 'TVGuide',
            show: true,
        },
        {
            id: 'PHONE',
            order: 3,
            resourceId: 'common_apps_phone_label',
            state: 'INDEX_PHONE',
            imageTag: 'phone',
            show: true,
        },
        {
            id: 'VIDEO_LIBRARY',
            order: 5,
            resourceId: 'common_apps_video_library_label',
            state: 'INDEX_VIDEO_LIBRARY',
            imageTag: 'education',
            show: true,
        },
        {
            id: 'MOVIES_ON_DEMAND',
            order: 6,
            resourceId: 'common_apps_mod_label',
            state: 'INDEX_MOVIES_ON_DEMAND',
            imageTag: 'moviesOnDemand',
            show: true,
        },
        {
            id: 'APPLICATION_SETTINGS',
            order: 8,
            resourceId: 'common_apps_settings_label',
            state: 'INDEX_SETTINGS_APPLICATION',
            imageTag: 'settings',
            show: true,
        },
        {
            id: 'SMART_ROOM',
            order: 8,
            resourceId: '',
            state: 'INDEX_SMARTROOM',
            imageTag: '',
            show: false,
        },
        {
            id: 'FRIENDS_FAMILY_COLLABORATION',
            order: 7,
            resourceId: 'common_apps_fnf_label',
            state: 'INDEX_CONTACTS',
            imageTag: 'friendsnfamily',
            show: true,
        },
        {
            id: 'VIDEO_APPS',
            order: 10,
            resourceId: '',
            state: '',
            imageTag: 'howTouseVideo',
            show: true,
        },
        {
            id: 'ENTERTAINMENT',
            order: 11,
            resourceId: 'common_apps_entertainment_label',
            state: 'INDEX_EXTERNAL_APPS',
            imageTag: 'entertainment',
            show: true,
        },
        {
            id: 'GAMES',
            order: 12,
            resourceId: 'common_apps_games_label',
            state: 'INDEX_EXTERNAL_APPS',
            imageTag: 'games',
            show: true,
        },
        {
            id: 'APPS',
            order: 13,
            resourceId: 'common.other-apps-label',
            state: 'INDEX_EXTERNAL_APPS',
            imageTag: 'otherapps',
            show: true,
        },
    ],
    PatientSpecificApps: ['MY_VISIT', 'PATIENT_SCHEDULE', 'GOALS', 'PATIENT_FEEDBACK', 'PATIENT_PROFILE'],
    applicationResponsiveConfig: [
        {
            breakpoint: 3900,
            settings: {
                slidesToShow: 5,
                slidesToScroll: 5,
            },
        },
        {
            breakpoint: 2600,
            settings: {
                slidesToShow: 5,
                slidesToScroll: 5,
            },
        },
        {
            breakpoint: 1920,
            settings: {
                slidesToShow: 4,
                slidesToScroll: 4,
            },
        },
        {
            breakpoint: 1280,
            settings: {
                slidesToShow: 3,
                slidesToScroll: 3,
            },
        },
        {
            breakpoint: 600,
            settings: {
                slidesToShow: 2,
                slidesToScroll: 2,
            },
        },
    ],
};
